### ISSUE TITLE
Move Elevator folder from frc/robot/subsystems/drive to frc/robot/subsystems

### ISSUE THREAD

**Issue by AkeBoss-tech** [Hateforks/Project#1]
You have the elevator subsystem in the wrong folder. Make sure to move them from here https://github.com/Hateforks/Project/tree/master/src/main/java/frc/robot/subsystems/drive to here https://github.com/Hateforks/Project/tree/master/src/main/java/frc/robot/subsystems/elevator

Make sure to refactor your code so that whenever you import the elevator, you use the correct path for it
https://github.com/Hateforks/Project/blob/master/src/main/java/frc/robot/RobotContainer.java
Update RobotContainer and the files in the Elevator folder for these changes

**Comment by shigureui2** [comment]
It has been done
